#!/usr/bin/env python
"""
Скрипт для добавления навыков (skills) в базу данных
"""
import os
import django

# Настройка Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'unicrewback.settings_production')
django.setup()

from backapp.models import Skill

# Список навыков для добавления
skills_list = [
    "Python",
    "JavaScript",
    "TypeScript",
    "Java",
    "C++",
    "C#",
    "Go",
    "PHP",
    "Kotlin",
    "Swift",
    "Rust",
    "SQL",
    "NoSQL",
    "Bash",
    "R",
    "HTML",
    "CSS",
    "SASS",
    "SCSS",
    "React",
    "Next.js",
    "Angular",
    "Vue.js",
    "Nuxt",
    "Svelte",
    "SolidJS",
    "Alpine.js",
    "TailwindCSS",
    "Bootstrap",
    "JQuery",
    "Django",
    "Django REST Framework",
    "Flask",
    "FastAPI",
    "Node.js",
    "Express.js",
    "NestJS",
    "Spring Boot",
    "Laravel",
    "Symfony",
    "Ruby",
    "Ruby on Rails",
    "ASP.NET",
    "GraphQL",
    "WebSockets",
    "WebRTC",
    "REST API",
    "gRPC",
    "PostgreSQL",
    "MySQL",
    "SQLite",
    "MongoDB",
    "Redis",
    "Firebase",
    "Supabase",
    "MariaDB",
    "Cassandra",
    "DynamoDB",
    "Elasticsearch",
    "ClickHouse",
    "Hadoop",
    "Spark",
    "Kafka",
    "Airflow",
    "Docker",
    "Docker Compose",
    "Kubernetes",
    "Helm",
    "Nginx",
    "Apache",
    "CI/CD",
    "GitHub Actions",
    "GitLab CI",
    "Bitbucket Pipelines",
    "Terraform",
    "Ansible",
    "Jenkins",
    "AWS",
    "GCP",
    "Azure",
    "Cloudflare",
    "Linux",
    "Ubuntu Server",
    "Shell Scripting",
    "Excel",
    "Power BI",
    "Tableau",
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "TensorFlow",
    "PyTorch",
    "Jupyter Notebook",
    "Data Analysis",
    "Data Engineering",
    "Machine Learning",
    "Deep Learning",
    "NLP",
    "Computer Vision",
    "MLOps",
    "LangChain",
    "LLM Fine-Tuning",
    "Flutter",
    "Dart",
    "React Native",
    "SwiftUI",
    "Jetpack Compose",
    "Unity",
    "Unreal Engine",
    "Figma",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe Premiere Pro",
    "After Effects",
    "Lightroom",
    "Blender",
    "Cinema 4D",
    "3ds Max",
    "UI/UX Design",
    "Prototyping",
    "Wireframing",
    "Interaction Design",
    "Motion Design",
    "Product Management",
    "Product Analytics",
    "A/B Testing",
    "Agile",
    "Scrum",
    "Kanban",
    "Roadmapping",
    "User Stories",
    "Business Analysis",
    "BPMN",
    "Jira",
    "Confluence",
    "Trello",
    "Notion",
    "Content Marketing",
    "SMM",
    "SEO",
    "SEM",
    "Google Analytics",
    "Google Ads",
    "Meta Ads",
    "TikTok Ads",
    "Email Marketing",
    "CRM Systems",
    "Copywriting",
    "Content Creation",
    "Targeting",
    "SQL Optimization",
    "Cybersecurity",
    "Penetration Testing",
    "Ethical Hacking",
    "OWASP",
    "SIEM",
    "Blockchain",
    "Solidity",
    "Smart Contracts",
    "Web3",
    "DevRel",
    "QA Testing",
    "Manual Testing",
    "Automated Testing",
    "Selenium",
    "Cypress",
    "Playwright",
    "Jest",
    "Pytest",
    "Mocha",
    "Chai",
]

def add_skills():
    """Добавляет навыки в базу данных"""
    created_count = 0
    existing_count = 0
    
    for skill_name in skills_list:
        skill, created = Skill.objects.get_or_create(name=skill_name)
        if created:
            created_count += 1
            print(f"✅ Создан навык: {skill_name}")
        else:
            existing_count += 1
            print(f"📝 Навык уже существует: {skill_name}")
    
    print("\n" + "="*50)
    print(f"✅ Создано новых навыков: {created_count}")
    print(f"📝 Существующих навыков: {existing_count}")
    print(f"📊 Всего навыков: {Skill.objects.count()}")
    print("="*50)

if __name__ == "__main__":
    add_skills()

