# Generated by Django 4.2.24 on 2025-09-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0003_rename_qualities_user_personal_qualities_customskill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_myself',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
