# Generated by Django 4.2.24 on 2025-09-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0005_school_faculty_alter_user_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='project',
            new_name='team',
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'user')},
        ),
    ]
