# Generated by Django 4.2.24 on 2025-09-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0006_rename_project_teammember_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидание'), ('INVITED', 'Приглашен'), ('APPROVED', 'Участник'), ('REJECTED', 'Отклонён')], default='PENDING', max_length=20),
        ),
    ]
