# Generated by Django 4.2.24 on 2025-10-11 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0007_alter_teammember_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='message',
            field=models.TextField(blank=True, help_text='Сообщение от пользователя при подаче заявки', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('TEAM_INVITATION', 'Приглашение в команду'), ('TEAM_REQUEST', 'Запрос на вступление'), ('TEAM_REQUEST_APPROVED', 'Заявка одобрена'), ('TEAM_REQUEST_REJECTED', 'Заявка отклонена'), ('TEAM_INVITATION_ACCEPTED', 'Приглашение принято'), ('TEAM_INVITATION_REJECTED', 'Приглашение отклонено')], max_length=30)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name='notifications', to='backapp.team')),
                ('team_member', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name='notifications', to='backapp.teammember')),
                ('user', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='notifications', to='backapp.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
