# Generated by Django 4.2.24 on 2025-10-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0008_auto_20251011_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='telegram_link',
            field=models.URLField(blank=True, help_text='Ссылка на группу Telegram', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='whatsapp_link',
            field=models.URLField(blank=True, help_text='Ссылка на группу WhatsApp', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='education_level',
            field=models.CharField(blank=True, choices=[('BACHELOR', 'Бакалавриат'), ('MASTER', 'Магистратура'), ('PHD', 'Докторантура'), ('OTHER', 'Другое')], default='BACHELOR', max_length=20, null=True),
        ),
    ]
