# Generated by Django 4.2.24 on 2025-10-27 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0009_team_telegram_link_team_whatsapp_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TEAM_INVITATION', 'Приглашение в команду'), ('TEAM_REQUEST', 'Запрос на вступление'), ('TEAM_REQUEST_APPROVED', 'Заявка одобрена'), ('TEAM_REQUEST_REJECTED', 'Заявка отклонена'), ('TEAM_INVITATION_ACCEPTED', 'Приглашение принято'), ('TEAM_INVITATION_REJECTED', 'Приглашение отклонено'), ('TASK_ASSIGNED', 'Задача назначена'), ('TASK_UPDATED', 'Задача обновлена')], max_length=30),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TODO', 'К выполнению'), ('IN_PROGRESS', 'В работе'), ('DONE', 'Выполнено'), ('CANCELLED', 'Отменено')], default='TODO', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Низкий'), ('MEDIUM', 'Средний'), ('HIGH', 'Высокий'), ('URGENT', 'Срочный')], default='MEDIUM', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='backapp.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='backapp.task'),
        ),
    ]
